### ISSUE TITLE
Installed via pip but having issues running

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/pychopper#1]
Traceback: OSError: dlopen(libparasail.dylib, 6): image not found

not sure how to solve

**Comment by bsipos** [comment]
Interesting. Which OS are you using?

**Comment by callumparr** [comment]
MacOS.

**Comment by bsipos** [comment]
The problem is with the installation of the [parasail](https://github.com/jeffdaily/parasail) dependency. Please try to re-install that, or install it from source.

**Comment by callumparr** [comment]
I installed from parasail source and still get same error:

tm1612s-MacBook-Pro:~ callum$ cdna_classifier.py -h
Traceback (most recent call last):
  File "/Users/callum/miniconda3/bin/cdna_classifier.py", line 4, in <module>
    __import__('pkg_resources').run_script('pychopper==0.1.0', 'cdna_classifier.py')
  File "/Users/callum/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/callum/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/Users/callum/miniconda3/lib/python3.6/site-packages/pychopper-0.1.0-py3.6.egg/EGG-INFO/scripts/cdna_classifier.py", line 9, in <module>
    from pychopper import chopper
  File "/Users/callum/miniconda3/lib/python3.6/site-packages/pychopper-0.1.0-py3.6.egg/pychopper/chopper.py", line 6, in <module>
    from pychopper import seq_detect
  File "/Users/callum/miniconda3/lib/python3.6/site-packages/pychopper-0.1.0-py3.6.egg/pychopper/seq_detect.py", line 5, in <module>
    import parasail
  File "/Users/callum/miniconda3/lib/python3.6/site-packages/parasail-1.1.12-py3.6.egg/parasail/__init__.py", line 30, in <module>
    _lib = ctypes.CDLL(_libname)
  File "/Users/callum/miniconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libparasail.dylib, 6): image not found

**Comment by callumparr** [comment]
I cannot find this lib parasail.dylib anywhere after successfully building from source using CMake.

**Comment by bsipos** [comment]
Could you raise this issue with the parasail developers please?
