### ISSUE TITLE
Error accoring when installing pychopper

### ISSUE THREAD

**Issue by ecross1** [nanoporetech/pychopper#29]
When installing pychopper we have an Error with this transcript. Can anyone explain where the error is or is coming from?

Error: 

 

(base) justincross@justincross-ThinkPad-T430:~/Downloads$ cdna_classifier.py --help 

Traceback (most recent call last): 

  File "/home/justincross/miniconda3/bin/cdna_classifier.py", line 4, in <module> 

    __import__('pkg_resources').run_script('pychopper==2.2.2', 'cdna_classifier.py') 

  File "/home/justincross/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script 

    self.require(requires)[0].run_script(script_name, ns) 

  File "/home/justincross/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script 

    .format(**locals()), 

pkg_resources.ResolutionError: Script 'scripts/cdna_classifier.py' not found in metadata at '/home/justincross/miniconda3/lib/python3.7/site-packages/pychopper-2.2.2.dist-info'

**Comment by bsipos** [comment]
Your conda environment might be broken. Please install into a fresh environment.
