### ISSUE TITLE
Error: ValueError: invalid literal for int() with base 10: 'such'

### ISSUE THREAD

**Issue by guosongjia** [nanoporetech/pychopper#32]
Dear all,
I want to use this software to identify full length reads from output fastq file. 
My command is:
```
$ cdna_classifier.py -r report.pdf -u unclassified.fq -w rescued.fq U571-01-N01_clean.fastq U571-01-Configurations to consider: "+:SSP,-VNP|-:VNP,-SSP"
Total fastq records in input file: 3126700
Tuning the cutoff parameter (q) on 10053 sampled reads (0.3%).
Optimizing over 30 cutoff values.
  0%|                                                                                                                                 | 0/30 [00:00<?, ?it/s]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/taoyutian/miniconda3/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/taoyutian/miniconda3/lib/python3.7/concurrent/futures/process.py", line 191, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/taoyutian/miniconda3/lib/python3.7/concurrent/futures/process.py", line 191, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/taoyutian/miniconda3/lib/python3.7/site-packages/pychopper/hmmer_backend.py", line 59, in _find_locations_single
    return list(_parse_hmmscan_tab(dout.decode().split("\n"), reads))
  File "/home/taoyutian/miniconda3/lib/python3.7/site-packages/pychopper/hmmer_backend.py", line 23, in _parse_hmmscan_tab
    hit = Hit(tmp[2], int(tmp[6]), int(tmp[7]) + 1, tmp[0], int(tmp[4]), int(tmp[5]) + 1, float(tmp[12]))
ValueError: invalid literal for int() with base 10: 'such'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/taoyutian/miniconda3/bin/cdna_classifier.py", line 278, in <module>
    for read, (segments, hits, usable_len) in backend(batch, executor, qv, max(1000, int((len(read_sample)) / args.t))):
  File "/home/taoyutian/miniconda3/lib/python3.7/site-packages/pychopper/chopper.py", line 102, in chopper_phmm
    for i, hits in enumerate(batch_hits):
  File "/home/taoyutian/miniconda3/lib/python3.7/site-packages/pychopper/hmmer_backend.py", line 36, in find_locations
    for res in pool.map(_find_locations_single, zip(batches, [(phmm_file, E, 1)] * len(batches))):
  File "/home/taoyutian/miniconda3/lib/python3.7/concurrent/futures/process.py", line 476, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/taoyutian/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/taoyutian/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/taoyutian/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: invalid literal for int() with base 10: 'such'
```
Can anyone help me to solve this problem?
Thanks!
Guo-Song

**Comment by bsipos** [comment]
Did you install pychopper from bioconda? If not I recommend doing so to make sure that you have the right version of hmmer.

Botond

**Comment by guosongjia** [comment]
> Did you install pychopper from bioconda? If not I recommend doing so to make sure that you have the right version of hmmer.
> 
> Botond

I installed the software following the README page using bioconda and I have checked the installation of the latest `hmmer` package. However, the error still occurs. 
The version of my `Python` is `Python 3.7.3 (default, Mar 27 2019, 22:11:17)` and I guess this error may occur because of the incompatibility between `pychopper` and `python`?
Thanks!
Guo-Song

**Comment by bsipos** [comment]
Could you please post here the hmmer version. Thanks.

**Comment by guosongjia** [comment]
> Could you please post here the hmmer version. Thanks.

The version of my `hmmer` is 3.1b2
```
$ hmmscan -h
# hmmscan :: search sequence(s) against a profile database
# HMMER 3.1b2 (February 2015); http://hmmer.org/
# Copyright (C) 2015 Howard Hughes Medical Institute.
# Freely distributed under the GNU General Public License (GPLv3).
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Usage: hmmscan [-options] <hmmdb> <seqfile>
```

**Comment by bsipos** [comment]
That is too old. Pychopper requires hmmer >= 3.2. Please install pychopper into a fresh conda environment and make sure you activate it before running the command.

**Comment by guosongjia** [comment]
> That is too old. Pychopper requires hmmer >= 3.2. Please install pychopper into a fresh conda environment and make sure you activate it before running the command.

Thanks for your advice！
I created a new `conda` environment and installed the latest version `hmmer` (v3.3) and the `pychopper`. It works well now!
Thank you!
Guo-Song
