### ISSUE TITLE
I get following error

### ISSUE THREAD

**Issue by guandailu** [nanoporetech/pychopper#55]
Using kit: PCS109
Configurations to consider: "+:SSP,-VNP|-:VNP,-SSP"
Traceback (most recent call last):
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/.snakemake/conda/ec1f5938/bin/cdna_classifier.py", line 336, in <module>
    nr_records = utils.count_fastq_records(args.input_fastx)
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/.snakemake/conda/ec1f5938/lib/python3.6/site-packages/pychopper/utils.py", line 57, in count_fastq_records
    b = fh.read(size)
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/.snakemake/conda/ec1f5938/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by philres** [comment]
Hi and thanks for you message.

could you please post the full command you used to run pychopper here. Also which version of pychopper you are using.

Is it possible you tried to run pychopper with a zipped fastq file?

Thanks,
Philipp

**Comment by guandailu** [comment]
Hi Thanks,

Just trying it with uncompressed fastq file, it works.

Thanks,
Dailu

**Comment by philres** [comment]
If you run:
```
pip install git+https://github.com/nanoporetech/pychopper.git
```
you should get the latest version of pychopper that supports gzipped inputs.

Best,
Philipp
