### ISSUE TITLE
pip install on Debian system 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/pychopper#8]
I got it working on my macOS environment and now I want to our HPC to start analyzing much larger files but I am stuck after installing. I can not see any error with install, 

After calling cdna_classifier.py -h 

I get error relating to numpy but no idea how to resolve. Maybe reinstalling numpy?

Traceback (most recent call last):
  File "./.local/bin/cdna_classifier.py", line 9, in <module>
    from pychopper import chopper
  File "/home/callum/.local/lib/python2.7/site-packages/pychopper/chopper.py", line 4, in <module>
    import numpy as np
  File "/home/callum/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/callum/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "/home/callum/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "/home/callum/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "/home/callum/.local/lib/python2.7/site-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

**Comment by bsipos** [comment]
Yes, it seems to be a numpy issue. You could try reinstalling it or using it from a conda env.

**Comment by callumparr** [comment]
Sorry issue was multiple installs/versions of numpy within site-packages. pip uninstall numpy interactions and then ran pip install pychopper again to install all dependencies
